Repository ngoworldcommunity/NGOWorld, pull requests merged in 2022-10, with the labels that each got.

#325 Fix:Updated navlinks, Now changes color on hover
  src/styles/Navbar.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🟨 priority: medium, ⭐ goal: addition, hacktoberfest-accepted

#338 fix: Necessary changes were done to enhance Docs
  CONTRIBUTING.md
  rules/FrontendSetup.md
Labels: 📄 aspect: text, ✨ goal: improvement, 🥗 status: ready for merge, 🟨 priority: medium, good first issue, hacktoberfest-accepted

#342 fix: Changes in ReadMe + License Update
  README.md
Labels: 📄 aspect: text, ✨ goal: improvement, 🥗 status: ready for merge, 🟨 priority: medium, hacktoberfest-accepted

#339 A tagline for clubs 🛠️
  server/index.js
  server/models/ClubsSchema.js
  server/routes/Clubs.js
  src/pages/clubs/ClubsRegister.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟨 priority: medium, ⭐ goal: addition, hacktoberfest-accepted

#348 Feature : Dockerize the web app 🛠
  Dockerfile
  docker-compose.yaml
  server/Dockerfile
  server/package.json
Labels: 🥗 status: ready for merge, 🟧 priority: high, 🤖 aspect: dx, ⭐ goal: addition, hacktoberfest-accepted

#353 Docs : Added docs for docker setup 📝
  README.md
  rules/DockerSetup.md
Labels: 📄 aspect: text, ✨ goal: improvement, 🥗 status: ready for merge, 🟨 priority: medium, hacktoberfest-accepted

#336 Accessibility : Highlighting errors in contact form
  src/pages/ContactUs.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#356 Fix : Added the link to Footer correctly
  server/routes/Clubs.js
  src/components/SocialIcons.jsx
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, good first issue, hacktoberfest-accepted

#357 fix: Added footer to each page
  src/pages/AboutUs.jsx
  src/pages/ContactUs.jsx
  src/pages/Donate.jsx
  src/pages/display/ClubsPage.jsx
  src/pages/display/EventsPage.jsx
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, good first issue, hacktoberfest-accepted

#358 Fixed the Date and Time sections of Create event
  src/pages/clubs/EventCreate.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, hacktoberfest-accepted

#359 A tagline for clubs 🏷️
  server/models/ClubsSchema.js
  src/pages/clubs/ClubsRegister.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, ⭐ goal: addition, hacktoberfest-accepted

#364 Updated footer to point to correct links
  src/components/Footer.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, good first issue, hacktoberfest-accepted

#365 Modified Report Button
  src/components/Footer.jsx
  src/styles/Footer.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🟨 priority: medium, ⭐ goal: addition, hacktoberfest-accepted

#363 Fix : Updates to textareas and copyrights 🛠
  public/index.html
  src/components/Footer.jsx
  src/pages/user/UserRegister.jsx
  src/styles/Footer.css
  src/styles/index.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, hacktoberfest-accepted

#373 Adding contact button to footer and removing from navbar
  src/components/Navbar.jsx
  src/components/SocialIcons.jsx
  src/styles/Footer.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, hacktoberfest-accepted

#383 Added Hover on Explore & Share Buttons(#369 Solved)
  src/components/DonateBanner.jsx
  src/components/Events.jsx
  src/styles/DonateBanner.css
  src/styles/Events.css
  src/styles/ShopHeader.css
Labels: 🥗 status: ready for merge, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, good first issue, hacktoberfest-accepted

#387 fix: Events page mobile #382
  src/pages/display/EventsPage.jsx
  src/styles/EventsPage.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, good first issue, hacktoberfest-accepted

#388 Fix : Changes to automation templates and more 🛠
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/pull_request_template.md
  .gitignore
  cypress/videos/1-getting-started/todo.cy.js.mp4
Labels: 🥗 status: ready for merge, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, 🤖 aspect: dx

#384 Improved Footer of home page
  package-lock.json
  public/index.html
  src/components/Footer.jsx
  src/styles/Footer.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 🕹 aspect: interface, 🟨 priority: medium, hacktoberfest-accepted

#394 Toast finally modified
  src/pages/Donate.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/clubs/EventCreate.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, hacktoberfest-accepted

#401 Ui minor fixes
  package-lock.json
  src/App.jsx
  src/components/Banners/Banner.jsx
  src/components/Banners/ClubBanner.jsx
  src/components/Banners/DonateBanner.jsx
  src/components/Banners/LoginBanner.jsx
  src/components/Cards/ProductsCard.jsx
  src/components/DonateBanner.jsx
  src/components/Events/SingleEvent.jsx
  src/components/Events/index.jsx
  src/components/Footer/index.jsx
  src/components/Headers/ShopHeader.jsx
  src/components/HomeCardsContainer.jsx
  src/components/HomeCardsContainer/index.jsx
  src/components/Navbar/index.jsx
  src/components/Products.jsx
  src/components/Products/index.jsx
  src/components/ProductsCard.jsx
  src/components/ShopHeader.jsx
  src/components/SingleClub/index.jsx
  src/components/SingleEvent.jsx
  src/components/SocialIcons.jsx
  src/components/SocialIcons/index.jsx
  src/components/index.jsx
  src/index.jsx
  src/pages/Home.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/display/EventsPage.jsx
  src/pages/index.jsx
  src/pages/shops/ShopLanding.jsx
  src/styles/ClubsPage.css
  src/styles/Navbar.css
  src/styles/index.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#399 [BUG FIX] Fixed the alignment of the social-btn
  src/styles/Footer.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#409 fix : Changes in credentials
  .github/pull_request_template.md
  .github/workflows/greetings.yml
  docker-compose.yaml
  server/Procfile
  src/assets/pictures/deba.png
  src/assets/pictures/parna.png
  src/assets/pictures/roy.png
Labels: 🟥 priority: critical, 🕹 aspect: interface, 🛠 goal: fix, 🤖 aspect: dx, 🛠 status : under development

#411 fix : added homepage tests for cypress
  cypress.config.js
  cypress/e2e/milan-tests/helloworld.cy.js
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🤖 aspect: dx, ⭐ goal: addition

#402 Fix: Login/register page design issues
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
  src/styles/ClubLogin.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, good first issue, hacktoberfest-accepted

#410 Home page button responsiveness
  src/styles/Banner.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#417 Added cypress tests and GitHub action config 🤖
  cypress/e2e/1-getting-started/todo.cy.js
  cypress/e2e/2-advanced-examples/actions.cy.js
  cypress/e2e/2-advanced-examples/aliasing.cy.js
  cypress/e2e/2-advanced-examples/assertions.cy.js
  cypress/e2e/2-advanced-examples/connectors.cy.js
  cypress/e2e/2-advanced-examples/cookies.cy.js
  cypress/e2e/2-advanced-examples/cypress_api.cy.js
  cypress/e2e/2-advanced-examples/files.cy.js
  cypress/e2e/2-advanced-examples/local_storage.cy.js
  cypress/e2e/2-advanced-examples/location.cy.js
  cypress/e2e/2-advanced-examples/misc.cy.js
  cypress/e2e/2-advanced-examples/navigation.cy.js
  cypress/e2e/2-advanced-examples/network_requests.cy.js
  cypress/e2e/2-advanced-examples/querying.cy.js
  cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  cypress/e2e/2-advanced-examples/traversal.cy.js
  cypress/e2e/2-advanced-examples/utilities.cy.js
  cypress/e2e/2-advanced-examples/viewport.cy.js
  cypress/e2e/2-advanced-examples/waiting.cy.js
  cypress/e2e/2-advanced-examples/window.cy.js
  cypress/e2e/milanTest.spec.js
  package.json
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟨 priority: medium, 🤖 aspect: dx, ⭐ goal: addition

#424 Forgot password page design 🛠
  src/App.jsx
  src/assets/pictures/forgotpass.svg
  src/assets/pictures/forgotpassworduser.svg
  src/pages/clubs/ClubForgotpassword.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/user/UserForgotpassword.jsx
  src/pages/user/UserLogin.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, ⭐ goal: addition, hacktoberfest-accepted

#421 Club and User Login Form UI Improvements, Better Transition
  src/pages/clubs/ClubsLogin.jsx
  src/pages/user/UserLogin.jsx
  src/styles/ClubLogin.css
  src/styles/UserLogin.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, hacktoberfest-accepted

#433 Fix : Fixed some typos and improved some sentences
  README.md
Labels: 📄 aspect: text, 🥗 status: ready for merge, 🟧 priority: high, 🛠 goal: fix, good first issue, hacktoberfest-accepted

#429 fix: Change in the text inside Toast after registering.
  src/pages/clubs/ClubsRegister.jsx
  src/pages/user/UserRegister.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#430 Fix: Moved JWT SECRET key to .env
  server/routes/User.js
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟥 priority: critical, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#436 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 📄 aspect: text, ✨ goal: improvement, 🥗 status: ready for merge, 🟧 priority: high, good first issue, hacktoberfest-accepted

#443 Added a new loader in Events page 🎉
  src/components/Loading/index.jsx
  src/pages/display/ClubsPage.jsx
  src/pages/display/EventsPage.jsx
  src/styles/Loading.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#432 Updated club cards 🎉
  src/styles/ClubsPage.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, ⭐ goal: addition, hacktoberfest-accepted

#434 Add back to top button on Home page
  src/components/Banners/Banner.jsx
  src/styles/Banner.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, ⭐ goal: addition, hacktoberfest-accepted

#437 fix-donate-page-auth-issue
  src/components/DonateUs.jsx
  src/pages/Donate.jsx
Labels: 🥗 status: ready for merge, hacktoberfest-accepted

#444 Changes Join links to Explore links if the user is logged in.
  src/components/Footer/index.jsx
Labels: 🥗 status: ready for merge, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, good first issue, hacktoberfest-accepted

#445 fix: landing page background attachment
  package-lock.json
  src/components/Banners/Banner.jsx
  src/styles/Banner.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, hacktoberfest-accepted

#448 Landing Page "Continue As" Buttons Styling Tweak
  src/components/Banners/Banner.jsx
  src/styles/Banner.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, good first issue, hacktoberfest-accepted

#452 Added Automated Cypress Tests to Github Workflows
  .github/workflows/cypress-tests.yml
  cypress.config.js
  src/components/Banners/Banner.jsx
  src/components/Cards/ProductsCard.jsx
  src/components/Footer/index.jsx
  src/pages/ContactUs.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟥 priority: critical, 🤖 aspect: dx, ⭐ goal: addition, hacktoberfest-accepted

#462 fix: corrected scroll button functionality
  src/components/Banners/Banner.jsx
  src/styles/Banner.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#468 DX : Added new cypress tests 🛠
  cypress/e2e/milanTest.spec.js
  package-lock.json
  server/routes/Clubs.js
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserProfile.jsx
  src/pages/user/UserRegister.jsx
  src/service/MilanApi.js
Labels: 🥗 status: ready for merge, 🟧 priority: high, 🕹 aspect: interface, 🤖 aspect: dx, ⭐ goal: addition

#476 fix: shop route active state CSS corrected
  src/components/Navbar/index.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#463 Automated linting using pre-commit/pre-push hooks
  .eslintignore
  .eslintrc.json
  .husky/pre-commit
  .husky/pre-push
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
  src/App.jsx
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🟨 priority: medium, 🤖 aspect: dx, hacktoberfest-accepted

#459 Updated Validation Methods For user's Login & Register
  package-lock.json
  package.json
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
  src/utils/validation.js
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#450 Bug:improved labels,placeholder update user page
  src/pages/user/UserProfile.jsx
  src/styles/UserLogin.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#487 DX : Seo and Cypress tests 🛠
  cypress/e2e/milanTest.spec.js
  package-lock.json
  package.json
  public/index.html
  public/sitemap.txt
  server/routes/Display.js
  src/index.jsx
  src/pages/ContactUs.jsx
  src/pages/Donate.jsx
  src/pages/Home.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/shops/ShopLanding.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🤖 aspect: dx

#488 fix: scroll back to top button behavior resolved
  package-lock.json
  src/components/Banners/Banner.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#465 Added hover effect on the product cards
  src/styles/ProductsCard.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, ⭐ goal: addition, hacktoberfest-accepted

#497 Sumbit button responsiveness
  package-lock.json
  src/styles/Footer.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, good first issue, hacktoberfest-accepted

#498 Fixed the unhandled promises in routes
  server/package-lock.json
  server/routes/Clubs.js
  server/routes/Display.js
  server/routes/Payment.js
  server/routes/User.js
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🛠 goal: fix, 🛠 status : under development, hacktoberfest-accepted

#500 fix: Update the guideline links
  README.md
Labels: 📄 aspect: text, 🥗 status: ready for merge, 🟧 priority: high, 🛠 goal: fix, hacktoberfest-accepted

#505 fix: replace class attribute to className
  src/components/Footer/index.jsx
  src/components/SingleClub/index.jsx
  src/pages/clubs/EventCreate.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🛠 goal: fix, good first issue, hacktoberfest-accepted

#511 Updates in Issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: 🥗 status: ready for merge, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, 🤖 aspect: dx, hacktoberfest-accepted

#512 Fixes for card overflowing issue
  src/components/Footer/index.jsx
  src/pages/display/ClubsPage.jsx
  src/styles/ClubsPage.css
  src/styles/Footer.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#514 Fix for footer in mobiles
  src/components/Footer/index.jsx
  src/styles/Footer.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#520 Fix for new events not created
  server/index.js
  server/routes/Clubs.js
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🛠 goal: fix, good first issue, hacktoberfest-accepted

#524 fix: duplicate toasts
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, hacktoberfest-accepted

#527 Donate page styling
  src/App.jsx
  src/pages/Donate.jsx
  src/pages/display/EventsPage.jsx
  src/styles/Donate.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, ⭐ goal: addition, hacktoberfest-accepted

#529 Fixed #513 > Event Card Issue !
  src/components/Events/SingleEvent.jsx
  src/pages/display/EventsPage.jsx
  src/styles/EventsPage.css
Labels: 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, 🛠 status : under development

#522 Minor changes to buttons
  src/styles/UserLogin.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🟨 priority: medium, ⭐ goal: addition, good first issue, hacktoberfest-accepted

#533 FEATURE: Taglines in Cards
  src/components/SingleClub/index.jsx
  src/styles/ClubsPage.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, hacktoberfest-accepted

#531 fix bug shop page responsive
  src/styles/ShopHeader.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, hacktoberfest-accepted
