Repository ngoworldcommunity/NGOWorld, pull requests merged in 2022-02, with the labels that each got.

#18 Added Login page
  pages/login.html
Labels: JWOC, Easy

#20 Banner text #14
  index.html
  styles/styles.css
Labels: JWOC, Easy

#24 Added Registration Form
  index.html
  milan/form.css
  milan/form.html
Labels: JWOC, Medium

#25 Make a Navbar !! #9
  index.html
  styles/styles.css
Labels: JWOC, Easy

#28 Added an about page with core team and contributors section with responsive styling.
  images/about-bg.jpg
  images/contributors/mridul.jpg
  images/core-team/Tamal.png
  images/dummy-profile.png
  images/icon-pack/github.png
  images/icon-pack/linkedin.png
  images/icon-pack/website.png
  index.html
  pages/about.html
  styles/about.css
Labels: JWOC, Medium

#27 Added Responsive Footer in the Homepage only
  index.html
  styles/footer.css
Labels: JWOC, Medium

#23 contact us page made
  contact us/con-styles.css
  contact us/contact-styles.css
  contact us/contact.html
  contact us/contact_us.html
Labels: JWOC, Medium

#35 Added user registration component for milan react-app.
  milan-app/package-lock.json
  milan-app/src/App.jsx
  milan-app/src/assets/pictures/register.jpg
  milan-app/src/components/Banner.jsx
  milan-app/src/pages/user/UserRegister.jsx
  milan-app/src/styles/UserRegister.css
Labels: JWOC, Hard

#34 Added clubs login component
  milan-app/src/App.jsx
  milan-app/src/assets/pictures/login-img-mobile.png
  milan-app/src/assets/pictures/login-img.png
  milan-app/src/pages/clubs/ClubsLogin.jsx
  milan-app/src/styles/ClubLogin.css
Labels: JWOC, Hard

#37 Clubs And Clubs Page
  milan-app/src/App.jsx
  milan-app/src/components/Banner.jsx
  milan-app/src/components/SingleClub.jsx
  milan-app/src/pages/display/CLUB_DATA.js
  milan-app/src/pages/display/ClubsPage.css
  milan-app/src/pages/display/ClubsPage.jsx
Labels: JWOC, Hard

#39 Adding the Userlogin page
  milan-app/src/App.jsx
  milan-app/src/components/Navbar.jsx
  milan-app/src/pages/user/UserLogin.jsx
  package-lock.json
Labels: JWOC, Medium

#43 Added club page responsiveness
  milan-app/package-lock.json
  milan-app/src/styles/ClubsPage.css
Labels: JWOC, Easy

#45 Added React-APP Club Register Page
  milan-app/src/App.jsx
  milan-app/src/assets/pictures/clubReg.png
  milan-app/src/components/Banner.jsx
  milan-app/src/components/ClubRegisterForm.jsx
  milan-app/src/components/PicUpload.jsx
  milan-app/src/components/TextArea.jsx
  milan-app/src/pages/clubs/ClubsRegister.jsx
  milan-app/src/styles/ClubForm.css
Labels: JWOC, Medium

#46 Added frontend login input verification
  milan-app/src/pages/user/UserLogin.jsx
Labels: JWOC, Easy

#51 Updated UI for user registration page according to user login page
  milan-app/src/pages/user/UserRegister.jsx
  milan-app/src/styles/UserRegister.css
Labels: JWOC, Medium

#52 Adding the footer component
  milan-app/package-lock.json
  milan-app/src/components/Footer.jsx
  milan-app/src/pages/Home.jsx
  milan-app/src/styles/Footer.css
Labels: JWOC, Easy

#53 🚀 feat: Added ContactUs Page
  milan-app/src/App.jsx
  milan-app/src/assets/pictures/contactusImage.png
  milan-app/src/components/Navbar.jsx
  milan-app/src/pages/ContactUs.jsx
  milan-app/src/styles/ContactUs.css
Labels: JWOC, Medium

#57 Update ClubsPage.css
  milan-app/src/styles/ClubsPage.css
Labels: JWOC, Easy

#60 Refactor
  milan-app/src/assets/pictures/footer-icon-top.png
  milan-app/src/assets/pictures/footer-icon.png
  milan-app/src/components/Footer.jsx
  milan-app/src/styles/Footer.css
Labels: JWOC, Easy

#56 Designed HomeCardsContainer component for Home page
  milan-app/package-lock.json
  milan-app/package.json
  milan-app/src/assets/pictures/bg-bottom.png
  milan-app/src/assets/pictures/cuate.png
  milan-app/src/assets/pictures/pana.png
  milan-app/src/components/HomeCardsContainer.jsx
  milan-app/src/styles/HomeCardsContainer.css
Labels: JWOC, Hard

#69 UI/UX - Styles fix
  milan-app/src/styles/ContactUs.css
Labels: JWOC, Medium

#70 UserSchema is added in server/models
  server/models/UserSchema.js
Labels: JWOC, Easy

#73 ClubsSchema is created in server/models
  server/models/ClubsSchema.js
Labels: JWOC, Easy

#72 Added Club Register Component
  milan-app/src/App.jsx
  milan-app/src/assets/pictures/clubRegistrationImage.png
  milan-app/src/pages/clubs/ClubsLogin.jsx
  milan-app/src/pages/clubs/ClubsRegister.jsx
  milan-app/src/styles/ClubsRegister.css
Labels: JWOC, Easy

#74 added new title and title logo
  milan-app/package-lock.json
  milan-app/public/favicon.ico
  milan-app/public/index.html
Labels: JWOC, Easy

#82 Designed donate-banner component for home page.
  milan-app/src/assets/pictures/donate-banner.png
  milan-app/src/components/DonateBanner.jsx
  milan-app/src/pages/Home.jsx
  milan-app/src/styles/DonateBanner.css
Labels: JWOC, Medium

#85 Show all clubs
  server/routes/Display.js
Labels: JWOC, Easy

#89 Fixed: Position of Report button in footer
  milan-app/src/styles/Footer.css
Labels: JWOC, Easy

#95 Added header and return home link
  milan-app/src/pages/ContactUs.jsx
  milan-app/src/styles/ContactUs.css
Labels: JWOC, Easy

#96 #94 Fixed font-style on about page
  milan-app/src/styles/AboutUs.css
Labels: JWOC, Easy

#97 Backend for user login
  server/routes/User.js
Labels: JWOC, Medium

#98 updated the events banner
  milan-app/package-lock.json
  milan-app/src/assets/pictures/eventCuate.png
  milan-app/src/assets/pictures/eventsBanner.svg
  milan-app/src/components/Events.jsx
  milan-app/src/pages/Home.jsx
  milan-app/src/styles/Events.css
Labels: JWOC, Medium

#99 Added backend route for club login
  server/package-lock.json
  server/routes/Clubs.js
Labels: JWOC, Medium, Assigned

#107 Fixed errors in user display and state and added backend integration for user registration
  milan-app/src/pages/user/UserLogin.jsx
  milan-app/src/pages/user/UserRegister.jsx
  milan-app/src/service/MilanApi.js
  milan-app/src/styles/UserLogin.css
Labels: JWOC, Hard

#109 Fixed bugs in club register form and state and added backend integration for club registration
  milan-app/src/pages/clubs/ClubsRegister.jsx
  milan-app/src/service/MilanApi.js
  server/routes/Clubs.js
Labels: JWOC, Hard

#108 Connected the user's login frontend to backend
  milan-app/package-lock.json
  milan-app/package.json
  milan-app/src/pages/user/UserLogin.jsx
  milan-app/src/service/MilanApi.js
  server/package-lock.json
  server/routes/User.js
Labels: JWOC, Hard

#114 Fix picture and content size for event section in home page
  milan-app/src/components/DonateBanner.jsx
  milan-app/src/components/Events.jsx
  milan-app/src/styles/DonateBanner.css
  milan-app/src/styles/Events.css
Labels: JWOC, Hard

#110 Connected the club's login frontend to backend
  milan-app/src/pages/clubs/ClubsLogin.jsx
  milan-app/src/service/MilanApi.js
  server/routes/Clubs.js
Labels: JWOC, Hard

#124 fix: Added Report API backend route with DB model
  CHANGELOG.md
  package-lock.json
  package.json
  server/models/ReportProblemSchema.js
  server/routes/User.js
Labels: JWOC, Easy

#131 fix: Noelle actions test
  actTEST.md
Labels: bug

#132 fix: Noelle actions test 3
  actTEST.md
Labels: chore

#134 fix: Contact us layout
  src/styles/ContactUs.css
Labels: bug, JWOC, Easy

#135 fix: Noelle actions test 4
  actTEST.md
Labels: bug

#137 feat: Introduced workflows
  actTEST.md
Labels: feature

#140 fix: updated footer responsiveness for all screens
  package-lock.json
  src/components/Footer.jsx
  src/styles/Footer.css
Labels: bug, JWOC, Easy, type: bug

#141 feat: updated version resolver to labels
  .github/release-drafter.yml
Labels: minor

#147 feat: added backend integration for fetching all clubs
  src/components/SingleClub.jsx
  src/pages/display/ClubsPage.jsx
  src/service/MilanApi.js
  src/styles/ClubsPage.css
Labels: JWOC, Medium, feature

#148 feat: Deployed backend
  server/.gitignore
  server/package-lock.json
  src/service/MilanApi.js
  src/styles/ClubsPage.css
Labels: feature

#149 fix: Updated report integration and added Report Modal
  package-lock.json
  src/components/Footer.jsx
  src/service/MilanApi.js
  src/styles/Footer.css
Labels: JWOC, Medium, feature

#153 fix: Report Modal glitches out
  src/components/Footer.jsx
  src/styles/Footer.css
Labels: bug, JWOC, Easy

#154 fix: resized buttons for smaller devices
  src/styles/Banner.css
Labels: bug, JWOC, Easy

#158 feat: added new banner upon auth
  package-lock.json
  src/assets/pictures/arrow.png
  src/assets/pictures/loginBanner.svg
  src/components/loginBanner.jsx
  src/pages/Home.jsx
  src/pages/user/UserLogin.jsx
  src/styles/LoginBanner.css
Labels: JWOC, Medium, feature

#159 fix: image sizing
  src/components/loginBanner.jsx
  src/styles/LoginBanner.css
Labels: bug

#167 feat: Added logout option in /user/profile route
  src/App.jsx
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/pages/Home.jsx
  src/pages/user/UserProfile.jsx
Labels: JWOC, Medium, feature

#166 fix: Resized font on smaller screens
  src/styles/LoginBanner.css
Labels: bug, JWOC, Easy
