Repository ngoworldcommunity/NGOWorld, pull requests merged in 2022-12, with the labels that each got.

#548 Authentication check on Donations page
  src/components/Banners/DonateBanner.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix

#552 Modify product cards design
  src/components/Cards/ProductsCard.jsx
  src/styles/ProductsCard.css
  src/styles/index.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix

#559 [Bug] Navbar issue solved
  src/pages/AboutUs.jsx
  src/pages/ContactUs.jsx
  src/pages/Donate.jsx
  src/pages/clubs/ClubForgotpassword.jsx
  src/pages/clubs/ClubProfile.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/clubs/EventCreate.jsx
  src/pages/shops/ShopLanding.jsx
  src/pages/user/UserForgotpassword.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserProfile.jsx
  src/pages/user/UserRegister.jsx
  src/styles/Navbar.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, Completed ✅

#561 Fix: Added footer in all the pages
  src/App.jsx
  src/pages/AboutUs.jsx
  src/pages/ContactUs.jsx
  src/pages/Donate.jsx
  src/pages/Home.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, ⭐ goal: addition, Completed ✅, good first issue

#563 Navbar SignUp and Logo issue solved
  src/components/Navbar.jsx
  src/styles/Navbar.css
Labels: 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, 🛠 status : under development
