Repository ngoworldcommunity/NGOWorld, pull requests merged in 2022-08, with the labels that each got.

#249 fix: Modify mobile styling for footer
  src/components/Footer.jsx
  src/components/SocialIcons.jsx
  src/styles/Footer.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, good first issue

#252 Added donations using razorpay ✅
  .env
  server/index.js
  server/package-lock.json
  server/package.json
  server/routes/Payment.js
  src/components/SingleClub.jsx
  src/pages/Donate.jsx
  src/pages/display/EventsPage.jsx
  src/service/PaymentGateway.js
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, ⭐ goal: addition

#258 Fixed banner differences [Donate/Event] page
  src/pages/display/EventsPage.jsx
  src/styles/ClubsPage.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium

#259 add a banner for clubs - #253
  README.md
  src/assets/pictures/clubs-banner.svg
  src/pages/display/ClubsPage.jsx
  src/styles/ClubsPage.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium

#260 Contact Page - Mobiles 📱
  src/pages/ContactUs.jsx
  src/pages/user/UserRegister.jsx
  src/styles/ContactUs.css
  src/styles/UserLogin.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium

#265 Use cookies on club login
  src/components/Navbar.jsx
  src/pages/Home.jsx
  src/pages/clubs/ClubProfile.jsx
  src/pages/clubs/ClubsLogin.jsx
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium

#271 fix: add placeholder text to input forms
  package-lock.json
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/user/UserLogin.jsx
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface

#274 Remove forget password from the user register page
  src/pages/user/UserRegister.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, good first issue

#277 Fix: Event page responsiveness
  src/pages/display/EventsPage.jsx
  src/styles/ClubsPage.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix

#279 feat : Changed from Heroku to vercel
  server/.gitignore
  server/vercel.json
  src/service/MilanApi.js
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🤖 aspect: dx, ⭐ goal: addition
