Repository ngoworldcommunity/NGOWorld, pull requests merged in 2022-07, with the labels that each got.

#202 fix:Report page
  package-lock.json
  src/components/Footer.jsx
  src/styles/Footer.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, Completed ✅

#203 fix: Home page issue
  src/styles/Banner.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🟥 priority: critical, 🕹 aspect: interface

#205 User Credential Update Feature
  server/index.js
  server/package-lock.json
  server/routes/User.js
  src/components/Footer.jsx
  src/components/SingleClub.jsx
  src/pages/user/UserProfile.jsx
  src/service/MilanApi.js
  src/styles/Navbar.css
  src/styles/UserLogin.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟥 priority: critical, ⭐ goal: addition, Completed ✅

#206 UI/UX Improvements - Homepage sections
  package-lock.json
  package.json
  src/components/DonateBanner.jsx
  src/components/Events.jsx
  src/styles/DonateBanner.css
  src/styles/Events.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 🕹 aspect: interface, 🟩 priority: low

#210 Added routes , ready for deploy C1
  package-lock.json
  server/db.js
  src/service/MilanApi.js
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟥 priority: critical, 🔒 staff only, 🛠 goal: fix, Completed ✅

#213 Fix 208
  src/components/Footer.jsx
  src/context/MilanState.js
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium

#212 Fix : Anchor tags 🛠
  src/components/Footer.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🛠 goal: fix, 🟨 priority: medium

#218 Fixed : Issue of Events Page
  server/package-lock.json
  src/components/Events.jsx
  src/components/Footer.jsx
  src/pages/display/EventsPage.jsx
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, good first issue

#219 Fixed the footer bugs !
  src/components/Footer.jsx
  src/styles/Footer.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, good first issue

#217 Fixed a small typo in Contributing.md
  CONTRIBUTING.md
Labels: 📄 aspect: text, 🥗 status: ready for merge, 🛠 goal: fix, 🟩 priority: low, good first issue

#225 Fixed LOGIN button bug on Club Login page !
  src/pages/clubs/ClubsLogin.jsx
  src/styles/ClubLogin.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 🕹 aspect: interface, 🟨 priority: medium, good first issue

#228 Code Enhancements and Minor fixes
  server/package-lock.json
  server/routes/User.js
  src/components/Footer.jsx
  src/pages/ContactUs.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserProfile.jsx
  src/pages/user/UserRegister.jsx
  src/service/MilanApi.js
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🟥 priority: critical, ⭐ goal: addition

#229 Fixed UserLogin Welcome Page !
  src/components/loginBanner.jsx
  src/styles/LoginBanner.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface

#232 Added new formats (Reg,Login)
  public/index.html
  server/routes/Clubs.js
  src/components/Navbar.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/user/UserRegister.jsx
  src/service/MilanApi.js
  src/styles/ClubsRegister.css
  src/styles/UserLogin.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, good first issue

#231 Implementation of Contact Page - FrontEnd to BackEnd Logic📝🗒️
  server/routes/User.js
  src/pages/ContactUs.jsx
  src/service/MilanApi.js
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🛠 goal: fix, 🟨 priority: medium, ⭐ goal: addition, Completed ✅

#233 Optimization 🚀
  src/assets/pictures/ClubUpperImage.svg
  src/components/SingleClub.jsx
  src/pages/Home.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/EventCreate.jsx
  src/service/MilanApi.js
  src/styles/LoginBanner.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, 🟩 priority: low

#238 Events related change
  src/components/SingleEvent.jsx
  src/pages/clubs/EventCreate.jsx
  src/service/MilanApi.js
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, good first issue

#239 Fix Mobile Responsiveness in Event Page
  src/pages/display/EventsPage.jsx
  src/styles/ClubsPage.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium

#240 Changes made to the donations page
  src/App.jsx
  src/assets/pictures/donate_image1.svg
  src/components/DonateBanner.jsx
  src/components/SingleClub.jsx
  src/pages/Donate.jsx
  src/styles/ClubsPage.css
  src/styles/Donate.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, ⭐ goal: addition

#241 Auth : Login/Logout re-used 🔐
  src/App.jsx
  src/assets/pictures/comingsoon.svg
  src/components/Navbar.jsx
  src/pages/clubs/ClubProfile.jsx
  src/pages/user/UserProfile.jsx
  src/styles/UserLogin.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🛠 goal: fix, 🟨 priority: medium, ⭐ goal: addition

#244 Club Login Banner and Navbar Event Link 🔗⚠️
  src/components/Navbar.jsx
  src/components/SingleEvent.jsx
  src/pages/Home.jsx
  src/pages/display/EventsPage.jsx
  src/styles/Navbar.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🛠 goal: fix, good first issue

#247 UI/UX - Contact Page 🎨
  src/assets/pictures/contactUs.svg
  src/pages/ContactUs.jsx
  src/pages/user/UserProfile.jsx
  src/styles/ContactUs.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, good first issue

#248 Added toasts
  package-lock.json
  package.json
  src/components/SingleClub.jsx
  src/pages/Donate.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/display/CLUB_DATA.js
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
  src/service/MilanApi.js
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, good first issue
