Repository ngoworldcommunity/NGOWorld, pull requests merged in 2022-06, with the labels that each got.

#194 Fix grammar and wording in README.md
  README.md
Labels: 📄 aspect: text, Completed ✅, good first issue

#195 updated the profile image breaking problem !
  package-lock.json
  package.json
  src/assets/pictures/ProfilePicture.png
  src/components/Navbar.jsx
Labels: 💻 aspect: code, 🛠 goal: fix, 🟨 priority: medium, Completed ✅, fix

#197 Updating Footer UI
  package-lock.json
  src/components/Footer.jsx
Labels: ✨ goal: improvement, 💻 aspect: code, 🟨 priority: medium, Completed ✅, fix

#198 #191 Fix : how the Contact Page looks
  src/pages/ContactUs.jsx
  src/styles/ContactUs.css
Labels: ✨ goal: improvement, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, Completed ✅, fix
