Repository ngoworldcommunity/NGOWorld, pull requests merged in 2022-09, with the labels that each got.

#281 docs: fix broken link and add proper tech stack
  README.md
  package-lock.json
Labels: 📄 aspect: text, ✨ goal: improvement, 🥗 status: ready for merge, 🛠 goal: fix, 🟨 priority: medium, good first issue

#284 Accessibility page titles
  src/components/Footer.jsx
  src/index.js
  src/pages/AboutUs.jsx
  src/pages/ContactUs.jsx
  src/pages/Donate.jsx
  src/pages/Home.jsx
  src/pages/clubs/ClubProfile.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/display/ClubsPage.jsx
  src/pages/display/EventsPage.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserProfile.jsx
  src/pages/user/UserRegister.jsx
  src/styles/index.css
Labels: 💻 aspect: code, 🛠 goal: fix, 🟨 priority: medium, 🛠 status : under development, good first issue

#288 Accessibility focusmanagement
  src/components/Banner.jsx
  src/components/DonateBanner.jsx
  src/components/Footer.jsx
  src/pages/ContactUs.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
  src/service/PaymentGateway.js
  src/styles/Banner.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, good first issue

#290 Color contrast changes
  src/components/Footer.jsx
  src/styles/DonateBanner.css
  src/styles/EventCreate.css
  src/styles/Events.css
  src/styles/Footer.css
  src/styles/HomeCardsContainer.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium

#291 Optimize the website - issue#282
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.jsx
  src/components/Banner.jsx
  src/components/Events.jsx
  src/components/Footer.jsx
  src/components/SingleClub.jsx
  src/pages/AboutUs.jsx
  src/pages/Home.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/clubs/EventCreate.jsx
  src/pages/user/UserLogin.jsx
  src/service/PaymentGateway.js
  src/styles/Banner.css
  src/styles/ClubLogin.css
  src/styles/ClubsPage.css
  src/styles/ClubsRegister.css
  src/styles/Donate.css
  src/styles/EventCreate.css
  src/styles/Footer.css
  src/styles/LoginBanner.css
  src/styles/Navbar.css
  src/styles/UserLogin.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium

#292 fix : aria labels, autofocus for mobiles
  src/pages/ContactUs.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
  src/styles/UserLogin.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🟨 priority: medium, good first issue

#293 Acessibility: close report modal with escape
  src/components/Footer.jsx
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium

#296 Docs: Added setup guidelines for backend
  README.md
  rules/BackendSetup.md
  rules/FrontendSetup.md
  rules/Setup.md
Labels: 📄 aspect: text, ✨ goal: improvement, 🥗 status: ready for merge, 🟧 priority: high, ⭐ goal: addition

#304 fix: #301- Labels for register club and minor updates
  src/pages/clubs/ClubsRegister.jsx
  src/styles/UserLogin.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 🕹 aspect: interface, 🟨 priority: medium, good first issue

#305 navigate to register
  package-lock.json
  src/components/Banner.jsx
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, good first issue

#303 Fix: User register placeholders
  src/pages/user/UserRegister.jsx
  src/styles/UserLogin.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, fix

#302 fix: navbar logo alt text
  src/components/Navbar.jsx
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, 🟩 priority: low, good first issue

#309 fixed identification of active menu in navbar issue
  src/components/Navbar.jsx
  src/styles/Navbar.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 🕹 aspect: interface, 🟨 priority: medium, ⭐ goal: addition

#307 Changed banner button grammar
  src/components/Banner.jsx
Labels: 📄 aspect: text, 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, good first issue

#317 Report modal data not cleared after submit/closed
  src/components/Footer.jsx
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, good first issue

#318 feat : Added new cypress tests
  cypress.config.js
  cypress/.eslintrc.json
  cypress/e2e/1-getting-started/todo.cy.js
  cypress/e2e/2-advanced-examples/actions.cy.js
  cypress/e2e/2-advanced-examples/aliasing.cy.js
  cypress/e2e/2-advanced-examples/assertions.cy.js
  cypress/e2e/2-advanced-examples/connectors.cy.js
  cypress/e2e/2-advanced-examples/cookies.cy.js
  cypress/e2e/2-advanced-examples/cypress_api.cy.js
  cypress/e2e/2-advanced-examples/files.cy.js
  cypress/e2e/2-advanced-examples/local_storage.cy.js
  cypress/e2e/2-advanced-examples/location.cy.js
  cypress/e2e/2-advanced-examples/misc.cy.js
  cypress/e2e/2-advanced-examples/navigation.cy.js
  cypress/e2e/2-advanced-examples/network_requests.cy.js
  cypress/e2e/2-advanced-examples/querying.cy.js
  cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  cypress/e2e/2-advanced-examples/traversal.cy.js
  cypress/e2e/2-advanced-examples/utilities.cy.js
  cypress/e2e/2-advanced-examples/viewport.cy.js
  cypress/e2e/2-advanced-examples/waiting.cy.js
  cypress/e2e/2-advanced-examples/window.cy.js
  cypress/e2e/milan-tests/helloworld.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  test1.md
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🟨 priority: medium, 🤖 aspect: dx, feature

#306 Changes in Headers
  src/components/Banner.jsx
  src/components/ClubBanner.jsx
  src/components/DonateBanner.jsx
  src/components/Events.jsx
  src/components/Footer.jsx
  src/components/HomeCardsContainer.jsx
  src/components/SingleClub.jsx
  src/components/SingleEvent.jsx
  src/pages/ContactUs.jsx
  src/pages/Donate.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/clubs/EventCreate.jsx
  src/pages/display/ClubsPage.jsx
  src/pages/display/EventsPage.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserProfile.jsx
  src/pages/user/UserRegister.jsx
  src/styles/ClubsPage.css
  src/styles/DonateBanner.css
  src/styles/Events.css
  src/styles/Footer.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium
