Repository ngoworldcommunity/NGOWorld, pull requests merged in 2022-03, with the labels that each got.

#175 events schema is added in server/model
  server/models/EventsSchema.js
Labels: JWOC, Easy, feature

#177 fix: resized club login form for mobiles
  src/pages/clubs/ClubsLogin.jsx
  src/styles/ClubLogin.css
Labels: bug, JWOC, Easy

#178 fix: Club section changes
  package-lock.json
  package.json
  src/pages/clubs/ClubsRegister.jsx
  src/styles/ClubsRegister.css
Labels: bug, JWOC, Medium

#179 Fix: Create Event page added with UI of given Figma file
  package-lock.json
  src/App.jsx
  src/assets/pictures/bro.png
  src/pages/clubs/EventCreate.jsx
  src/styles/EventCreate.css
Labels: JWOC, Medium, feature

#176 fix: UI fix in user register page
  src/pages/user/UserRegister.jsx
  src/styles/Footer.css
Labels: bug, JWOC, Easy

#180 Added new events banner upon club auth
  src/assets/pictures/clubCuate.svg
  src/components/ClubBanner.jsx
  src/pages/Home.jsx
  src/pages/clubs/ClubsLogin.jsx
Labels: JWOC, Easy, feature

#183 Backend of EventsApi
  server/models/EventsSchema.js
  server/routes/Clubs.js
Labels: JWOC, Medium, feature

#184 fix: Created contactUsSchema and a new route
  server/models/ContactUsSchema.js
  server/routes/User.js
Labels: JWOC, Hard, feature
