Repository ngoworldcommunity/NGOWorld, pull requests merged in 2023-10, with the labels that each got.

#1115 fix: signup button border hover effect
  src/components/Button/GlobalButton/Button.module.css
Labels: 🟢 status: ready to merge, area/ui, 🐞 bug, hacktoberfest-accepted, deployed

#1116 fix: removed unnecessary api call from events page
  src/pages/Event/AllEvents/Events.jsx
Labels: 🟢 status: ready to merge, area/logic, 🐞 bug, hacktoberfest-accepted, deployed

#1114 fix: remove hover effect on back to top button
  src/components/Button/BacktoTop/BacktoTop.css
Labels: 🟢 status: ready to merge, area/ui, 🐞 bug, hacktoberfest-accepted, deployed

#1112 feat: added iframe code input field to club sign in
  src/hooks/useValidation.js
  src/pages/Auth/AuthSignup.jsx
Labels: 🟢 status: ready to merge, area/logic, 💡 feature, hacktoberfest-accepted, deployed

#1122 fix: fix layout (footer & button)
  src/components/Cards/SingleClubEvent/SingleClubEvent.css
  src/components/Footer/Footer.css
Labels: status: ready ☑, 🐞 bug, hacktoberfest-accepted

#1113 feat: improve clubs page accessibility
  src/components/Cards/SingleClubEvent/SingleClubEvent.css
  src/components/Cards/SingleClubEvent/SingleClubEvent.jsx
  src/components/PageHeader/Header.jsx
  src/pages/Club/AllClubs/Clubs.css
  src/pages/Club/AllClubs/Clubs.jsx
Labels: status: ready ☑, 💡 feature, hacktoberfest-accepted

#1079 fix: cookies functionality, hyperlinks and shown appropriate content in footer
  src/components/Banners/HomeBanner.jsx
  src/components/Footer/Footer.jsx
  src/pages/Donate/Donate.jsx
Labels: status: ready ☑, 🐞 bug, hacktoberfest-accepted

#1137 fix: remove number circles from homepage
  src/components/Banners/Banner.css
  src/components/Banners/Milaninfobanner.jsx
Labels: status: ready ☑, 🐞 bug, hacktoberfest-accepted

#1146 docs: added definition of conventional pr link
  README.md
Labels: 📚 docs, status: ready ☑, hacktoberfest-accepted

#1140 fix: fixed functioning of contact us button in footer
  src/assets/data/ApiEndpoints.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Modal/Modal.jsx
Labels: status: ready ☑, 🐞 bug, hacktoberfest-accepted

#1154 docs: added a link that leads to the official docker desktop downloading documentation
  docs/DockerSetup.md
Labels: 📚 docs, status: ready ☑, hacktoberfest-accepted
