Repository ngoworldcommunity/NGOWorld, pull requests merged in 2023-07, with the labels that each got.

#913 fix: console log removed
  src/pages/clubs/ClubDetails.jsx
  src/service/MilanApi.js
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🛠 goal: fix, 🟨 priority: medium, deployed, gssoc23, level1

#909 feat: primary theme for site with vendor prefix
  index.html
Labels: 🛠 goal: fix, ⭐ goal: addition, deployed, ✨ aspect: accessibility, gssoc23, level1

#906 fix: error page overflow issue
  src/components/Footer.jsx
  src/pages/user/UserRegister.jsx
  src/styles/Error404.css
Labels: 🕹 aspect: interface, 🛠 goal: fix, deployed, gssoc23, level1

#922 fix: added navbar closing when clicking navlinks
  src/components/Navbar.jsx
Labels: 🥗 status: ready for merge, 🛠 goal: fix, deployed, gssoc23, level1

#852 feat: search clubs and events based on location and places
  server/index.js
  src/components/SingleClubEvent.jsx
  src/pages/AboutUs.jsx
  src/pages/display/ClubsPage.jsx
  src/pages/display/EventsPage.jsx
  src/pages/display/StatesData.js
  src/styles/ClubsPage.css
  src/styles/EventsPage.css
  src/utils/filter.js
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, ⭐ goal: addition, deployed, 📈 Major changes

#948 feat: location based search (#852)
  server/index.js
  src/components/Banners/Banner.jsx
  src/components/Navbar.jsx
  src/components/SingleClubEvent.jsx
  src/pages/AboutUs.jsx
  src/pages/display/ClubsPage.jsx
  src/pages/display/EventsPage.jsx
  src/pages/display/StatesData.js
  src/styles/App.css
  src/styles/Banner.css
  src/styles/Button.module.css
  src/styles/ClubsPage.css
  src/styles/EventsPage.css
  src/styles/Navbar.css
  src/utils/filter.js
Labels: 🦀 Staff only, ⭐ goal: addition, 🛠 status: Under development, deployed, 📈 Major changes

#849 feat: google authentication frontend
  server/.env.example
  server/config/passport-googleAuth-strategy.js
  server/index.js
  server/routes/user/Auth.js
  src/assets/pictures/authpages/google.png
  src/pages/user/UserLogin.jsx
  src/pages/user/UserProfile.jsx
  src/pages/user/UserRegister.jsx
  src/service/MilanApi.js
  src/styles/UserLogin.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, ⭐ goal: addition, deployed, 📈 Major changes, gssoc23, level3

#961 docs: update dependabot workflow
  .github/dependabot.yml
Labels: 📄 aspect: docs, 🥗 status: ready for merge, 🛠 goal: fix, deployed, gssoc23, level1

#942 fix: added footer to homepage.
  src/pages/Home.jsx
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, deployed, gssoc23, level1

#976 fix: changes to issue forms and socials
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  README.md
  SECURITY.md
  rules/DockerSetup.md
  src/components/Banners/Banner.jsx
  src/components/Footer.jsx
  src/components/SocialIcons/index.jsx
Labels: 🥗 status: ready for merge, 🦀 Staff only, 🛠 goal: fix, deployed

#944 feat: scroll to top button
  src/App.jsx
  src/components/Button/BacktoTop/BacktoTop.css
  src/components/Button/BacktoTop/BacktoTop.jsx
Labels: 🕹 aspect: interface, ⭐ goal: addition, 🚦 status: requested changes, deployed, gssoc23, level1
