Repository ngoworldcommunity/NGOWorld, pull requests merged in 2023-01, with the labels that each got.

#569 Cypress tests for Preview, Prod
  .env
  .github/workflows/cypress-tests.yml
  .github/workflows/prodtest.yml
  .github/workflows/prtests.yml
  cypress.config.js
  cypress/e2e/milanTest.spec.js
  package-lock.json
  package.json
  src/components/Banners/Banner.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  vercel.json
Labels: 💻 aspect: code, 🟥 priority: critical, 🔒 staff only, 🤖 aspect: dx, ⭐ goal: addition, 🛠 status : under development, deployed

#573 Hacktoberfest labels removed from issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/labels.json
  README.md
Labels: 💻 aspect: code, 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx, 🛠 status : under development, deployed

#572 Fix : Auth page layout consistency using CSS
  src/pages/clubs/ClubForgotpassword.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/user/UserForgotpassword.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
  src/styles/ClubLogin.css
  src/styles/ClubsRegister.css
  src/styles/UserLogin.css
Labels: ✨ goal: improvement, 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, 🚦 status: Requested changes, 🛠 status : under development, deployed

#579 [DOCS] Starting on local host
  rules/FrontendSetup.md
Labels: 📄 aspect: text, 🥗 status: ready for merge, deployed
