Repository ngoworldcommunity/NGOWorld, pull requests merged in 2023-04, with the labels that each got.

#614 refactor: refactor the button and tagline component in clubdetails.css
  src/styles/ClubDetails.css
Labels: deployed

#615 refactor: improved modal
  index.html
  src/components/Footer.jsx
  src/components/Modal.jsx
  src/styles/Footer.css
  src/styles/Modal.module.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, deployed

#622 fix: typos throughout the codebase & .gitignore
  .gitignore
  README.md
  SECURITY.md
  package-lock.json
  server/models/ContactUsSchema.js
  src/components/Footer.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
  src/service/MilanApi.js
  src/styles/App.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🛠 goal: fix, 🤖 aspect: dx

#630 fix: product card overflow
  package-lock.json
  package.json
  src/App.jsx
  src/components/Banners/Banner.jsx
  src/components/Cards/ProductsCard.jsx
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/components/shop/Products.jsx
  src/pages/Home.jsx
  src/pages/display/CLUB_DATA.js
  src/pages/display/ClubsPage.jsx
  src/pages/display/EventsPage.jsx
  src/pages/shops/ShopCategory.jsx
  src/pages/shops/ShopLanding.jsx
  src/styles/Banner.css
  src/styles/ClubDetails.css
  src/styles/ClubsPage.css
  src/styles/ContactUs.css
  src/styles/Loading.css
  src/styles/Products.css
  src/styles/ShopLanding.css
  src/styles/UserLogin.css
  src/styles/index.css
  src/utils/validation.js
Labels: 🥗 status: ready for merge, 🟧 priority: high, 🛠 goal: fix, deployed

#619 fix: contact page bug #616
  src/components/Footer.jsx
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, deployed

#631 style: changed looks of user register page
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, 🟩 priority: low, good first issue, deployed

#638 fix: sign up problem
  .eslintrc.js
  src/pages/user/UserRegister.jsx
  src/utils/showToast.js
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟥 priority: critical, 🛠 goal: fix

#633 fix: header alignment for Events page #626
  src/styles/ClubsPage.css
  src/styles/ShopLanding.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, good first issue, deployed

#654 docs: updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 📄 aspect: docs, 🥗 status: ready for merge, 🛠 goal: fix, 🟨 priority: medium, deployed
