Repository ngoworldcommunity/NGOWorld, pull requests merged in 2023-03, with the labels that each got.

#600 fix: navbar bug on inspect in signup page
  src/pages/user/UserRegister.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, deployed

#598 [FIX] : Made detailed club page responsive
  src/components/SingleClubEvent.jsx
  src/pages/clubs/ClubDetails.jsx
  src/styles/ClubDetails.css
  src/styles/Donate.css
Labels: 🥗 status: ready for merge, 💻 aspect: code, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, deployed

#611 fix: ui for report modal
  src/components/Footer.jsx
  src/styles/App.css
  src/styles/Footer.css
  src/styles/Navbar.css
Labels: 🥗 status: ready for merge, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, deployed
