Repository ngoworldcommunity/NGOWorld, pull requests merged in 2023-06, with the labels that each got.

#797 fix: update GitHub username to correct broken link
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: 📄 aspect: docs, 🥗 status: ready for merge, 🟧 priority: high, 🛠 goal: fix, deployed, gssoc23, level2

#788 fix: close navbar on clicking outside
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/context/MilanState.jsx
  src/utils/clickAwayListener.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🛠 goal: fix, 🟨 priority: medium, deployed, gssoc23, level2

#806 feat: added api to fetch single product
  server/routes/Products.js
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🟨 priority: medium, ⭐ goal: addition, deployed, gssoc23, level2

#819 feat: google authentication backend
  .env.example
  server/config/passport-googleAuth-strategy.js
  server/index.js
  server/models/UserSchema.js
  server/package-lock.json
  server/package.json
  server/routes/User.js
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🟨 priority: medium, ⭐ goal: addition, deployed, 📈 major-changes, gssoc23, level3

#826 feat: add FormatPrice component
  src/components/Cards/ProductsCard.jsx
  src/components/Helpers/FormatPrice.js
Labels: 💻 aspect: code logic, 🟨 priority: medium, ⭐ goal: addition, 🚦 status: requested changes, deployed, gssoc23, level2

#834 chore(refactor): changes to folders and configs
  server/config/passport-googleAuth-strategy.js
  server/index.js
  server/models/ReportProblemSchema.js
  server/package-lock.json
  server/routes/club/Club.js
  server/routes/display/Display.js
  server/routes/payment/Payment.js
  server/routes/shop/Products.js
  server/routes/user/Auth.js
  server/routes/user/User.js
  server/schema/club/ClubSchema.js
  server/schema/club/EventSchema.js
  server/schema/shop/ProductSchema.js
  server/schema/user/ContactUsSchema.js
  server/schema/user/ReportProblemSchema.js
  server/schema/user/UserSchema.js
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🟧 priority: high, 🔒 staff only, 🛠 goal: fix, deployed

#818 fix: changes for grammatical and spelling errors
  CONTRIBUTING.md
  rules/BackendSetup.md
  rules/CloneSetup.md
  rules/FrontendSetup.md
  src/components/Banners/Banner.jsx
  src/components/Events/index.jsx
  src/components/Footer.jsx
  src/components/Milaninfobanner.jsx
  src/pages/AboutUs.jsx
  src/pages/Donate.jsx
  src/pages/shops/ShopCategory.jsx
Labels: 📄 aspect: docs, 🛠 goal: fix, 🟨 priority: medium, 🚦 status: requested changes, deployed, 📈 major-changes, gssoc23, level2

#838 docs(contributing.md): upgrades to contributing file
  CONTRIBUTING.md
Labels: 📄 aspect: docs, 🥗 status: ready for merge, 🛠 goal: fix, 🟨 priority: medium, deployed, gssoc23, level1

#836 feat: added hover state on navbar
  src/styles/Navbar.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🟩 priority: low, ⭐ goal: addition, deployed, gssoc23, level1

#814 fix: added pincode validation and corrected responsiveness of signup page.
  src/pages/user/UserRegister.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🟧 priority: high, 🛠 goal: fix, deployed, gssoc23, level2

#832 fix: resolved clubs heading responsiveness issue
  src/styles/ClubsPage.css
Labels: 🥗 status: ready for merge, 🛠 goal: fix, 🟨 priority: medium, deployed, ✨ aspect: accessibility, gssoc23, level1

#857 style(button's banner): fix size of buttons
  src/styles/Banner.css
Labels: 🥗 status: ready for merge, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, deployed, gssoc23, level1

#877 feat: added custom validation hooks
  server/routes/user/User.js
  server/schema/club/ClubSchema.js
  server/schema/user/UserSchema.js
  src/hooks/useValidation.js
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
  src/service/MilanApi.js
Labels: 💻 aspect: code logic, 🔒 staff only, ⭐ goal: addition, 🛠 status: under development, deployed, 👷🏻‍♂️ status: awaiting triage

#859 fix: meta tags added
  index.html
Labels: 🥗 status: ready for merge, 🛠 goal: fix, deployed, ✨ aspect: accessibility, gssoc23, level2

#883 feat: added sticky navbar
  src/styles/Banner.css
  src/styles/ClubsPage.css
  src/styles/Navbar.css
  src/styles/ShopLanding.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, ⭐ goal: addition, deployed, gssoc23, level1

#874 feat: custom selection color text and background
  src/styles/App.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, ⭐ goal: addition, deployed, gssoc23, level2

#893 feat(docs): create sitemap.xml
  public/sitemap.xml
Labels: 📄 aspect: docs, 🥗 status: ready for merge, ⭐ goal: addition, deployed, gssoc23, level2

#862 fix: alt attributes added
  src/assets/pictures/donate-banner-image.svg
  src/components/Banners/ClubBanner.jsx
  src/components/Banners/DonateBanner.jsx
  src/components/Banners/LoginBanner.jsx
  src/components/Cards/ProductsCard.jsx
  src/components/Footer.jsx
  src/components/Milaninfobanner.jsx
  src/components/Navbar.jsx
  src/components/SingleClubEvent.jsx
  src/pages/AboutUs.jsx
  src/pages/ContactUs.jsx
  src/pages/Donate.jsx
  src/pages/clubs/ClubDetails.jsx
  src/pages/clubs/ClubForgotpassword.jsx
  src/pages/clubs/ClubProfile.jsx
  src/pages/clubs/EventCreate.jsx
  src/pages/user/UserForgotpassword.jsx
  src/pages/user/UserProfile.jsx
Labels: 🛠 goal: fix, 🛠 status: under development, deployed, ✨ aspect: accessibility, gssoc23, level2

#892 feat: revamping authentication
  cypress/e2e/milanTest.spec.js
  package-lock.json
  package.json
  server/routes/club/Club.js
  src/App.jsx
  src/assets/pictures/authpages/AuthBanner.jpg
  src/assets/pictures/authpages/Auth_banner.png
  src/assets/pictures/authpages/authbannerimg.svg
  src/assets/pictures/donate-banner-image.svg
  src/components/Banners/ClubBanner.jsx
  src/components/Banners/DonateBanner.jsx
  src/components/Banners/LoginBanner.jsx
  src/components/Button.jsx
  src/components/Button/AuthButton.jsx
  src/components/Cards/ProductsCard.jsx
  src/components/Footer.jsx
  src/components/Milaninfobanner.jsx
  src/components/Navbar.jsx
  src/components/SingleClubEvent.jsx
  src/hooks/useValidation.js
  src/pages/AboutUs.jsx
  src/pages/ContactUs.jsx
  src/pages/Donate.jsx
  src/pages/Home.jsx
  src/pages/auth/AuthPage.css
  src/pages/auth/clubs/ClubsLogin.jsx
  src/pages/auth/clubs/ClubsRegister.jsx
  src/pages/auth/user/UserLogin.jsx
  src/pages/auth/user/UserRegister.jsx
  src/pages/clubs/ClubDetails.jsx
  src/pages/clubs/ClubForgotpassword.jsx
  src/pages/clubs/ClubProfile.jsx
  src/pages/clubs/EventCreate.jsx
  src/pages/display/ClubsPage.jsx
  src/pages/display/EventsPage.jsx
  src/pages/index.jsx
  src/pages/shops/ShopLanding.jsx
  src/pages/user/UserForgotpassword.jsx
  src/pages/user/UserProfile.jsx
  src/service/MilanApi.js
  src/styles/App.css
  src/styles/ClubDetails.css
  src/styles/ClubsRegister.css
  src/styles/Footer.css
  src/styles/UserLogin.css
Labels: 🔒 staff only, 🛠 status: under development, deployed, 📈 major-changes
