Repository ngoworldcommunity/NGOWorld, pull requests merged in 2023-05, with the labels that each got.

#649 fix: adds explicit width and height to images
  src/components/Milaninfobanner.jsx
Labels: 🥗 status: ready for merge, 🛠 goal: fix, deployed, ✨ aspect: accessibility

#657 feat: add scrollTo functionality to shop, home, and club pages
  src/pages/Home.jsx
  src/pages/display/ClubsPage.jsx
  src/pages/display/EventsPage.jsx
  src/pages/shops/ShopLanding.jsx
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, good first issue, deployed

#661 docs: added links to repo setup page
  rules/CloneSetup.md
Labels: 📄 aspect: docs, 🥗 status: ready for merge, 🟧 priority: high, 🛠 goal: fix, deployed

#662 feat: changed npm to pnpm in frontend
  .github/workflows/prodtest.yml
  .github/workflows/prtests.yml
  package-lock.json
  package.json
  pnpm-lock.yaml
  server/package-lock.json
Labels: 💻 aspect: code logic, 🟧 priority: high, 🛠 status : under development, deployed, 👷‍♂️ goal: major

#664 feat: add signup popup
  src/components/Banners/Banner.jsx
  src/components/Navbar.jsx
  src/context/MilanState.jsx
  src/styles/Navbar.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🟨 priority: medium, ⭐ goal: addition, deployed

#668 fix: failing cypress test
  cypress/e2e/milanTest.spec.js
  src/components/Navbar.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#666 docs: added proper variable names for razorpay documentation
  rules/BackendSetup.md
Labels: 📄 aspect: docs, 🥗 status: ready for merge, 🟧 priority: high, ⭐ goal: addition, deployed

#669 feat: made changes to add 'Cross' symbol to toggle the navbar OFF in mobile view
  package-lock.json
  package.json
  src/components/Navbar.jsx
  src/context/MilanState.jsx
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🟨 priority: medium, ⭐ goal: addition, deployed

#691 fix: custom button component to fix inconsistency
  src/components/Banners/Banner.jsx
  src/components/Banners/DonateBanner.jsx
  src/components/Button.jsx
  src/components/Footer.jsx
  src/components/Milaninfobanner.jsx
  src/components/Navbar.jsx
  src/components/SingleClubEvent.jsx
  src/pages/Donate.jsx
  src/pages/clubs/ClubDetails.jsx
  src/pages/clubs/ClubForgotpassword.jsx
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/display/EventsPage.jsx
  src/pages/user/UserForgotpassword.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
  src/styles/Banner.css
  src/styles/Button.module.css
  src/styles/ClubLogin.css
  src/styles/ClubsPage.css
  src/styles/Footer.css
  src/styles/Milaninfobanner.css
  src/styles/Navbar.css
  src/styles/ShopLanding.css
  src/styles/UserLogin.css
Labels: 🥗 status: ready for merge, 🟧 priority: high, 🕹 aspect: interface, 🛠 goal: fix, deployed

#663 style: updated footer layout and style
  src/components/Footer.jsx
  src/styles/Footer.css
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🛠 goal: fix, 🟨 priority: medium, deployed

#740 feat: added sign In button to navbar
  src/components/Navbar.jsx
  src/context/MilanState.jsx
  src/styles/Button.module.css
  src/styles/Navbar.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🟩 priority: low, ⭐ goal: addition, deployed, gssoc23, level2

#763 feat: add sample .env file
  .env.example
  rules/BackendSetup.md
Labels: 🥗 status: ready for merge, 🟧 priority: high, ⭐ goal: addition, deployed, gssoc23, level2

#753 fix: improved the styling of social icons
  src/styles/Footer.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, 🟩 priority: low, deployed, gssoc23, level1

#745 feat(products): add API to add products
  package-lock.json
  server/index.js
  server/models/ProductSchema.js
  server/routes/Products.js
  vite.config.js
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🟧 priority: high, ⭐ goal: addition, deployed, gssoc23, level3

#737 docs: added readme badges
  README.md
Labels: 📄 aspect: docs, 🥗 status: ready for merge, 🟩 priority: low, ⭐ goal: addition, deployed, gssoc23, level1

#755 feat: password visibility toggle button added
  src/pages/clubs/ClubsLogin.jsx
  src/pages/clubs/ClubsRegister.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserRegister.jsx
  src/styles/UserLogin.css
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🕹 aspect: interface, 🟨 priority: medium, ⭐ goal: addition, deployed, gssoc23, level3

#773 feat: updated the "here" link in the footer - issue#761
  src/components/Footer.jsx
  src/styles/Footer.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, ⭐ goal: addition, deployed, gssoc23, level1

#767 feat: added company name after logo image and hover effect in nav-links
  src/components/Navbar.jsx
  src/styles/Navbar.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🟩 priority: low, ⭐ goal: addition, deployed, gssoc23, level1

#769 feat(products): add API to fetch all products
  server/routes/Products.js
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🟨 priority: medium, ⭐ goal: addition, deployed, gssoc23, level2
