Repository ngoworldcommunity/NGOWorld, pull requests merged in 2023-09, with the labels that each got.

#1067 fix: adress breakdown when signing up
  package-lock.json
  package.json
  src/App.jsx
  src/assets/data/ApiEndpoints.js
  src/assets/data/CountryList.js
  src/assets/data/Test_data.js
  src/assets/data/routesConfig.jsx
  src/assets/data/shop/Art_Data.js
  src/assets/data/shop/Shop_Data.js
  src/components/Cards/SingleClubEvent/SingleClubEvent.css
  src/components/Cards/SingleClubEvent/SingleClubEvent.jsx
  src/hooks/useValidation.js
  src/pages/Auth/AuthFormmodule.js
  src/pages/Auth/AuthLogin.jsx
  src/pages/Auth/AuthPage.css
  src/pages/Auth/AuthRegister.jsx
  src/pages/Club/AllClubs/Clubs.jsx
  src/pages/Club/Details/ClubDetails.css
  src/pages/Club/Details/ClubDetails.jsx
  src/pages/Event/AllEvents/Events.jsx
  src/pages/route.js
  src/service/MilanApi.js
Labels: 🦀 Staff only, 🐞 Bug, deployed, 👷🏻‍♂️ status: awaiting triage, Beta Release

#1068 feat: changes to auth & clubs
  .github/workflows/release-drafter.yml
  .gitignore
  docs/DockerSetup.md
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/assets/data/ApiEndpoints.js
  src/assets/data/CountryList.js
  src/assets/data/Test_data.js
  src/assets/data/routesConfig.jsx
  src/assets/data/shop/Art_Data.js
  src/assets/data/shop/Shop_Data.js
  src/components/Banners/HomeBanner.jsx
  src/components/Button/AuthButton/AuthButton.jsx
  src/components/Button/AuthButton/TopButton.jsx
  src/components/Button/GlobalButton/Button.jsx
  src/components/Cards/ComingSoon/ComingSoon.jsx
  src/components/Cards/SingleClubEvent/SingleClubEvent.css
  src/components/Cards/SingleClubEvent/SingleClubEvent.jsx
  src/components/Footer/Footer.jsx
  src/components/Navbar/Navbar.jsx
  src/components/SocialIcons/index.jsx
  src/hooks/useValidation.js
  src/pages/Auth/AuthFormmodule.js
  src/pages/Auth/AuthLogin.jsx
  src/pages/Auth/AuthPage.css
  src/pages/Auth/AuthSignup.jsx
  src/pages/Club/AllClubs/Clubs.jsx
  src/pages/Club/Details/ClubDetails.css
  src/pages/Club/Details/ClubDetails.jsx
  src/pages/Event/AllEvents/Events.jsx
  src/pages/User/UserProfile.jsx
  src/pages/route.js
  src/service/MilanApi.js
  src/utils/Cookies.js
  src/utils/Filter.js
Labels: 🛠 Feature, deployed, 👷🏻‍♂️ status: awaiting triage, Production Release

#1076 fix: footer elements not centered
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🐞 Bug, deployed

#1085 feat: added website field to club registration and details page
  src/hooks/useValidation.js
  src/pages/Auth/AuthFormmodule.js
  src/pages/Auth/AuthSignup.jsx
  src/pages/Club/Details/ClubDetails.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🛠 Feature, deployed
