Repository ngoworldcommunity/NGOWorld, pull requests merged in 2023-02, with the labels that each got.

#586 Removed additional information from all issue template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: 🥗 status: ready for merge, 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx, deployed

#588 [FEAT] : Single club page
  .gitignore
  server/routes/Clubs.js
  server/routes/Display.js
  src/App.jsx
  src/components/Navbar.jsx
  src/components/SingleClubEvent.jsx
  src/pages/clubs/ClubDetails.jsx
  src/service/MilanApi.js
  src/styles/ClubDetails.css
Labels: 💻 aspect: code, 🟧 priority: high, 🕹 aspect: interface, 🔒 staff only, 🛠 goal: fix, 🛠 status : under development, deployed

#590 Fix: Register button focus and register input box-shadow
  src/styles/UserLogin.css
Labels: ✨ goal: improvement, 🥗 status: ready for merge, 🕹 aspect: interface, 🟨 priority: medium, 🚦 status: Requested changes, 🛠 status : under development, deployed

#591 Show Explore Button when signed In.
  src/components/Banners/Banner.jsx
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 🛠 goal: fix, 🟨 priority: medium, deployed

#581 added footer
  package-lock.json
  package.json
  src/App.jsx
  src/components/Footer.jsx
  src/styles/Footer.css
Labels: 💻 aspect: code, 🕹 aspect: interface, 🟨 priority: medium, ⭐ goal: addition, 🚦 status: Requested changes, 🛠 status : under development, deployed
