Repository ngoworldcommunity/NGOWorld, pull requests merged in 2023-08, with the labels that each got.

#951 feat: google authentication frontend (#849)
  server/.env.example
  server/config/passport-googleAuth-strategy.js
  server/index.js
  server/routes/club/Club.js
  server/routes/user/Auth.js
  server/routes/user/User.js
  src/App.jsx
  src/assets/pictures/authpages/authbannerimg.webp
  src/assets/pictures/authpages/google.png
  src/components/Banners/Banner.jsx
  src/components/Button/AuthButton/AuthButton.jsx
  src/components/Button/AuthButton/TopButton.jsx
  src/components/Button/BacktoTop/BacktoTop.css
  src/components/Button/BacktoTop/BacktoTop.jsx
  src/components/Button/GlobalButton/Button.jsx
  src/components/Button/GlobalButton/Button.module.css
  src/components/Footer.jsx
  src/components/Milaninfobanner.jsx
  src/components/Navbar.jsx
  src/components/SingleClubEvent.jsx
  src/pages/Error404.jsx
  src/pages/Home.jsx
  src/pages/auth/AuthPage.css
  src/pages/auth/clubs/ClubsLogin.jsx
  src/pages/auth/clubs/ClubsRegister.jsx
  src/pages/auth/user/UserLogin.jsx
  src/pages/auth/user/UserRegister.jsx
  src/pages/display/ClubsPage.jsx
  src/pages/display/EventsPage.jsx
  src/pages/user/UserForgotpassword.jsx
  src/pages/user/UserLogin.jsx
  src/pages/user/UserProfile.jsx
  src/pages/user/UserRegister.jsx
  src/service/MilanApi.js
  src/styles/UserLogin.css
Labels: 🦀 Staff only, ⭐ goal: addition, deployed, 📈 Major changes

#974 docs: added links of official documentations
  README.md
Labels: 📄 aspect: docs, 🥗 status: ready for merge, ⭐ goal: addition, deployed, gssoc23, level1

#1003 fix: added correct link on the footer section
  src/components/Footer/Footer.jsx
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🛠 goal: fix, deployed, gssoc23, level1, Beta Release

#938 feat: add to cart api added
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/invitation.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/labeler-config.yml
  .github/release-drafter.yml
  .github/workflows/greetings.yml
  .github/workflows/invite.yml
  .github/workflows/release-drafter.yml
  package-lock.json
  package.json
  server/routes/shop/Products.js
  server/schema/shop/ProductSchema.js
  server/schema/user/UserSchema.js
  src/assets/pictures/authpages/Auth_banner.png
  src/assets/pictures/authpages/google.png
  src/assets/pictures/shop/handmades/h4.png
  src/assets/pictures/shop/handmades/handmades/h4.png
  src/assets/pictures/shop/trendingproducts/art/artproduct4.png
Labels: deployed, gssoc23, level3

#1025 fix: 4 tagline irregularity in small size
  src/components/Banners/Banner.css
Labels: 🥗 status: ready for merge, 🕹 aspect: interface, 📈 Patch, deployed, gssoc23, level1

#1033 feat: docker build and changes to issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  Dockerfile
  docker-compose.dev.yaml
  docker-compose.yaml
  package.json
  vite.config.js
Labels: 🦀 Staff only, 📈 Patch, 📈 Minor, 👷🏻‍♂️ status: awaiting triage, Beta Release

#1034 feat: docker setup and documentations
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/invitation.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/MilanReadmeBanner.png
  .github/pull_request_template.md
  .github/workflows/add-labels-to-pr.yml
  .github/workflows/auto-author-assign.yml
  .github/workflows/greetings.yml
  .github/workflows/invite.yml
  .github/workflows/prodtest.yml
  .github/workflows/prodtestbeta.yml
  .github/workflows/prtestbeta.yml
  .github/workflows/prtests.yml
  .github/workflows/prtitle-lint.yml
  .github/workflows/release-drafter.yml
  CONTRIBUTING.md
  Dockerfile
  README.md
  docker-compose.dev.yaml
  docker-compose.yaml
  docs/BackendSetup.md
  docs/CloneSetup.md
  docs/DockerSetup.md
  docs/FrontendSetup.md
  docs/Workflow.md
  package.json
  rules/CloneSetup.md
  server/routes/shop/Products.js
  server/schema/shop/ProductSchema.js
  server/schema/user/UserSchema.js
  vite.config.js
Labels: 💻 aspect: code logic, 🦀 Staff only, 📈 Minor, deployed, 👷🏻‍♂️ status: awaiting triage, Production Release

#1041 feat: merging the authentication pages of 2 different types of users into a single one
  src/App.jsx
  src/components/Banners/HomeBanner.jsx
  src/components/Button/AuthButton/TopButton.jsx
  src/components/Button/GlobalButton/Button.jsx
  src/components/Navbar/Navbar.jsx
  src/hooks/useValidation.js
  src/pages/Auth/AuthLogin.jsx
  src/pages/Auth/AuthPage.css
  src/pages/Auth/AuthRegister.jsx
  src/pages/Auth/Club/ClubsLogin.jsx
  src/pages/Auth/Club/ClubsRegister.jsx
  src/pages/Auth/User/UserRegister.jsx
  src/pages/route.js
Labels: 🥗 status: ready for merge, 🛠 Feature, deployed, Beta Release

#1010 chore: improve .gitignore and remove .DS_Store
  .DS_Store
  .gitignore
Labels: 🐞 Bug, 🤖 aspect: dx, 🚦 status: requested changes, deployed, gssoc23, level1

#1049 fix: no heading tags in footer
  src/components/Footer/Footer.jsx
Labels: 🥗 status: ready for merge, 🐞 Bug, deployed, Beta Release

#1057 fix: zipcode lenght issue for registration
  src/hooks/useValidation.js
Labels: 🥗 status: ready for merge, 💻 aspect: code logic, 🐞 Bug, Beta Release

#1056 fix: go back button return to home
  src/components/Button/AuthButton/TopButton.jsx
Labels: 🥗 status: ready for merge, 🐞 Bug, deployed, Beta Release

#1063 fix: removing code duplicacies in authentication
  package-lock.json
  package.json
  src/App.jsx
  src/pages/Auth/AuthFormmodule.js
  src/pages/Auth/AuthLogin.jsx
  src/pages/Auth/AuthRegister.jsx
  src/pages/Home.jsx
  src/store.js
  src/utils/routesConfig.jsx
Labels: 💻 aspect: code logic, 🐞 Bug, deployed, 👷🏻‍♂️ status: awaiting triage, Beta Release

#1047 feat: changes made to authentication
  .DS_Store
  .gitignore
  README.md
  cypress/e2e/milanTest.spec.js
  package-lock.json
  package.json
  src/App.jsx
  src/components/Banners/HomeBanner.jsx
  src/components/Button/AuthButton/AuthButton.jsx
  src/components/Button/AuthButton/TopButton.jsx
  src/components/Button/GlobalButton/Button.jsx
  src/components/Footer/Footer.jsx
  src/components/Navbar/Navbar.jsx
  src/hooks/useValidation.js
  src/pages/Auth/AuthFormmodule.js
  src/pages/Auth/AuthLogin.jsx
  src/pages/Auth/AuthPage.css
  src/pages/Auth/AuthRegister.jsx
  src/pages/Auth/Club/ClubsRegister.jsx
  src/pages/Auth/User/UserLogin.jsx
  src/pages/Auth/User/UserRegister.jsx
  src/pages/Club/AllClubs/Clubs.jsx
  src/pages/Home.jsx
  src/pages/route.js
  src/store.js
  src/utils/routesConfig.jsx
Labels: 🦀 Staff only, 🛠 Feature, deployed, Production Release
